#!/usr/bin/env python3
# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.
"""Dependency / license inventory (MIGRATION_AND_UPSTREAM §8, FR-B13).

Writes docs/project-hub/LICENSE_INVENTORY.md from:
* `pnpm licenses list --json --prod` (JS workspace, needs installed node_modules)
* installed Python distributions matching apps/api/requirements/base.txt (needs the API venv active)
The inventory documents obligations; it is not a legal clearance (L01 stays open).
"""

import json
import pathlib
import re
import subprocess
import sys
from importlib import metadata

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs/project-hub/LICENSE_INVENTORY.md"


def js_licenses():
    res = subprocess.run(["pnpm", "licenses", "list", "--json", "--prod"], cwd=ROOT, capture_output=True, text=True)
    if res.returncode != 0:
        return None, res.stderr.strip()[:500]
    data = json.loads(res.stdout or "{}")
    return {lic: sorted({p["name"] for p in pkgs}) for lic, pkgs in data.items()}, ""


def py_licenses():
    names = []
    for line in (ROOT / "apps/api/requirements/base.txt").read_text().splitlines():
        line = line.split("#")[0].strip()
        if not line or line.startswith("-"):
            continue
        names.append(re.split(r"[=<>\[ ]", line)[0])
    result = {}
    for name in names:
        try:
            meta = metadata.metadata(name)
            lic = meta.get("License-Expression") or meta.get("License") or ""
            if not lic or len(lic) > 60:
                classifiers = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or [] if c.startswith("License")]
                lic = ", ".join(classifiers) or (lic[:60] if lic else "UNKNOWN")
        except metadata.PackageNotFoundError:
            lic = "NOT INSTALLED (not verified)"
        result.setdefault(lic, []).append(name)
    return result


def main():
    js, js_err = js_licenses()
    py = py_licenses()
    lines = [
        "# Dependency and license inventory",
        "",
        "Generated by `tools/project-hub/license_inventory.py`. Documents obligations only; "
        "it is **not** a legal clearance. The fork itself is AGPL-3.0-only (see `LICENSE.txt`); "
        "L01 (distribution path) remains open.",
        "",
        "New runtime dependencies introduced by Project Hub: **none** (the Django extension uses existing "
        "backend packages; `apps/runner` is stdlib-only; the web UI uses existing workspace packages). "
        "Test-only: `jsonschema` (MIT) for contract validation, if listed in `apps/api/requirements/test.txt`.",
        "",
        "## JavaScript (production dependencies of the pnpm workspace)",
        "",
    ]
    if js is None:
        lines.append(f"_Not generated: {js_err or 'pnpm unavailable'}_")
    else:
        for lic in sorted(js):
            pkgs = js[lic]
            lines.append(f"- **{lic}** ({len(pkgs)}): " + ", ".join(pkgs[:40]) + (" …" if len(pkgs) > 40 else ""))
    lines += ["", "## Python (apps/api/requirements/base.txt)", ""]
    for lic in sorted(py):
        lines.append(f"- **{lic}**: " + ", ".join(sorted(py[lic])))
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
