#!/usr/bin/env python3
# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.
"""Requirement traceability (PRD §10 "each requirement has at least one checkable case").

Maps every FR-* of docs/project-hub/prd/foundation/requirement-map.json and every
acceptance scenario (AC01-AC32, PF01-PF14) to
* implementation references: files under the extension that mention the ID, and
* tests: test functions whose name or docstring mention the ID
  (``test_ac05_...``, ``test_pf06_...``, ``test_fr_g06_...`` or "FR-G06" in a docstring).

Writes docs/project-hub/TRACEABILITY.md and exits 1 if any requirement or
scenario has no test (use --allow-missing to only report).
"""

import argparse
import ast
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
REQ_MAP = ROOT / "docs/project-hub/prd/foundation/requirement-map.json"
FEATURES = [ROOT / "docs/project-hub/prd/acceptance/core.feature", ROOT / "docs/project-hub/prd/acceptance/plane-foundation.feature"]
CODE_DIRS = [
    ROOT / "apps/api/plane/package_flow",
    ROOT / "apps/runner/project_hub_runner",
    ROOT / "apps/web/core/components/project-hub",
    ROOT / "apps/web/core/store/project-hub",
    ROOT / "apps/web/core/services/project-hub",
    ROOT / "docs/project-hub",
    ROOT / "tools/project-hub",
]
TEST_DIRS = [ROOT / "apps/api/plane/tests/package_flow", ROOT / "apps/runner/tests"]
TS_TEST_DIRS = [ROOT / "apps/live/tests", ROOT / "packages/utils/src/project-hub", ROOT / "apps/web/e2e"]
OUT = ROOT / "docs/project-hub/TRACEABILITY.md"
SKIP_DOC_FILES = {"TRACEABILITY.md"}


def norm(req_id):
    """FR-G06 -> fr_g06 ; AC05 -> ac05 ; PF06 -> pf06"""
    return req_id.lower().replace("-", "_")


def test_index():
    tests = []
    for d in TEST_DIRS:
        for f in sorted(d.rglob("test_*.py")):
            tree = ast.parse(f.read_text())
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_"):
                    doc = ast.get_docstring(node) or ""
                    tests.append((f.relative_to(ROOT).as_posix(), node.name, node.name.lower() + " " + doc))
            # class-level docstrings also count for all their methods
            for node in tree.body:
                if isinstance(node, ast.ClassDef):
                    cdoc = ast.get_docstring(node) or ""
                    for m in node.body:
                        if isinstance(m, ast.FunctionDef) and m.name.startswith("test_"):
                            tests.append((f.relative_to(ROOT).as_posix(), f"{node.name}.{m.name}", cdoc))
    for d in TS_TEST_DIRS:
        if not d.exists():
            continue
        for f in sorted(list(d.rglob("*.test.ts")) + list(d.rglob("*.spec.ts"))):
            for title in re.findall(r"""\b(?:it|test)\(\s*["'`](.+?)["'`]""", f.read_text()):
                tests.append((f.relative_to(ROOT).as_posix(), title, title))
    return tests


def code_refs(req_id):
    pattern = re.compile(re.escape(req_id) + r"\b")
    hits = []
    for d in CODE_DIRS:
        if not d.exists():
            continue
        for f in d.rglob("*"):
            if not f.is_file() or f.suffix not in {".py", ".ts", ".tsx", ".md"} or "prd" in f.parts:
                continue
            if f.name in SKIP_DOC_FILES:
                continue
            try:
                if pattern.search(f.read_text(errors="ignore")):
                    hits.append(f.relative_to(ROOT).as_posix())
            except OSError:
                continue
    return sorted(set(hits))


def matching_tests(req_id, tests):
    key = norm(req_id)
    rx = re.compile(r"(^|[^a-z0-9])" + re.escape(key) + r"($|[^0-9])")
    raw = re.compile(re.escape(req_id) + r"\b")
    return sorted({f"{f}::{name}" for f, name, text in tests if rx.search(text.lower()) or raw.search(text)})


def scenarios():
    """[(scenario_id, title, [FR ids tagged on the scenario])]"""
    result = []
    for f in FEATURES:
        tag, frs = None, []
        for line in f.read_text().splitlines():
            m = re.match(r"\s*@((?:AC|PF)\d\d)", line)
            if m:
                tag = m.group(1)
                frs = re.findall(r"@(FR-[A-Z]\d\d)", line)
                continue
            m = re.match(r"\s*Szenario:\s*(.*)", line)
            if m and tag:
                result.append((tag, m.group(1).strip(), frs))
                tag, frs = None, []
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--allow-missing", action="store_true")
    args = parser.parse_args()
    reqs = json.loads(REQ_MAP.read_text())["requirements"]
    tests = test_index()
    lines = [
        "# Requirement and scenario traceability",
        "",
        "Generated by `tools/project-hub/traceability.py` from the PRD requirement map, the Gherkin "
        "scenarios and the actual test functions. A listed test is an executed automated test in "
        "`apps/api/plane/tests/package_flow` or `apps/runner/tests`; results of the last run are in "
        "`VERIFICATION.md`. Human usability checks, live provider contract tests and load tests are "
        "not automated tests and are tracked in `VERIFICATION.md` as open.",
        "",
        "## Acceptance scenarios",
        "",
        "| Scenario | Title | Tests |",
        "|---|---|---|",
    ]
    missing = []
    scen = scenarios()
    via_scenario = {}
    for tag, _title, frs in scen:
        for fr in frs:
            via_scenario.setdefault(fr, []).extend(f"{t} (via {tag})" for t in matching_tests(tag, tests))
    for tag, title, _frs in scen:
        found = matching_tests(tag, tests)
        if not found:
            missing.append(tag)
        lines.append(f"| {tag} | {title} | " + ("<br>".join(f"`{t}`" for t in found) or "**none**") + " |")
    lines += ["", "## Functional requirements", "", "| ID | Treatment | Implementation refs | Tests |", "|---|---|---|---|"]
    for r in reqs:
        rid = r["requirementId"]
        found = matching_tests(rid, tests) + sorted(set(via_scenario.get(rid, [])))
        refs = code_refs(rid)
        if not found:
            missing.append(rid)
        lines.append(
            f"| {rid} | {r['implementationTreatment']} | "
            + ("<br>".join(f"`{x}`" for x in refs[:6]) + (" …" if len(refs) > 6 else "") or "—")
            + " | "
            + ("<br>".join(f"`{t}`" for t in found[:6]) + (f" (+{len(found) - 6})" if len(found) > 6 else "") or "**none**")
            + " |"
        )
    lines += ["", f"Requirements/scenarios without automated test: {', '.join(missing) if missing else 'none'}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}; missing: {missing}")
    return 1 if missing and not args.allow_missing else 0


if __name__ == "__main__":
    sys.exit(main())
